export const ActionType = {
    SET_PRODUCTS: "SET_PRODUCTS",
    ADD_TO_CART:"ADD_TO_CART",
    QTY_INCREMENT_PRODUCT:"QTY_INCREMENT_PRODUCT",
    QTY_DECREMENT_PRODUCT:"QTY_DECREMENT_PRODUCT",
     REMOVE_CART_PRODUCT:"REMOVE_CART_PRODUCT",
}